apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "postgres_db"
  DB_USER: "postgres_user"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
